# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# TARGET
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/gate/world/daughters/name                  	target
/gate/world/daughters/insert                	box
/gate/target/setMaterial               	Steel304
/gate/target/geometry/setXLength          	0.01 cm
/gate/target/geometry/setYLength          	5 cm
/gate/target/geometry/setZLength       	5 cm
/gate/target/placement/setTranslation  	354.855 0.0 0.0 cm
/gate/target/placement/setRotationAxis     	0 1 0
/gate/target/placement/setRotationAngle   	45 deg
/gate/target/vis/setColor              	yellow
/gate/target/vis/forceSolid			
/gate/target/vis/setVisible 			1


