
#=====================================================
# VERBOSITY
#=====================================================

/control/execute mac/verbose.mac

#=====================================================
# VISUALISATION
#=====================================================

#/control/execute mac/visu.mac

# =====================================================
# GEOMETRY
# =====================================================

/gate/geometry/setMaterialDatabase   data/GateMaterials_INER.db

# -----------------------------------------------------
# WORLD
# -----------------------------------------------------

/gate/world/setMaterial            Vacuum
/gate/world/geometry/setXLength    2 m
/gate/world/geometry/setYLength    2 m
/gate/world/geometry/setZLength    2 m

# -----------------------------------------------------
# TARGET
# -----------------------------------------------------

/gate/world/daughters/name                  	target
/gate/world/daughters/insert                	box
/gate/target/setMaterial               	Vacuum
/gate/target/geometry/setXLength          	0.01 cm
/gate/target/geometry/setYLength          	5 cm
/gate/target/geometry/setZLength       	5 cm
/gate/target/placement/setTranslation  	0. 0.0 0.0 cm
/gate/target/placement/setRotationAxis     	0 1 0
/gate/target/placement/setRotationAngle   	45 deg
/gate/target/vis/setColor              	yellow
/gate/target/vis/forceSolid			
/gate/target/vis/setVisible 			1

# -----------------------------------------------------
# VIRTUAL PLANE FOR PHASE SPACE
# -----------------------------------------------------

/gate/world/daughters/name               	PhS_1m
/gate/world/daughters/insert                	sphere
/gate/PhS_1m/setMaterial               	Vacuum
/gate/PhS_1m/geometry/setRmin         		1 m
/gate/PhS_1m/geometry/setRmax 	          	1.0001 m
/gate/PhS_1m/placement/setTranslation 		0.0 0.0 0.0 cm
/gate/PhS_1m/vis/setVisible 			1
/gate/PhS_1m/vis/setColor			cyan
/gate/PhS_1m/vis/forceWireframe
/gate/PhS_1m/vis/setLineStyle			dashed

# =====================================================
# PHYSICS:
# =====================================================

/gate/physics/addPhysicsList 		QGSP_BIC_HP_EMY

/gate/physics/Gamma/SetCutInRegion      world 0.1 mm
/gate/physics/Electron/SetCutInRegion   world 0.1 mm
/gate/physics/Positron/SetCutInRegion   world 0.1 mm

#=====================================================
# DETECTORS:
#=====================================================

# ----------------------------------------------------
# the following actor regularly store the current number of event/track/step in a file
# ----------------------------------------------------

/gate/actor/addActor               		SimulationStatisticActor stat
/gate/actor/stat/save              		output/output-PhS.txt
/gate/actor/stat/saveEveryNSeconds 		20

# ----------------------------------------------------
# Phase space storage (a PhS for all particles)
# ----------------------------------------------------

/gate/actor/addActor                           PhaseSpaceActor  PhS_enter1
/gate/actor/PhS_enter1/attachTo                PhS_1m
/gate/actor/PhS_enter1/save 	               output/Particle_30MeV_5_5mm_neutron.root
/gate/actor/PhS_enter1/useVolumeFrame          true

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize

#=====================================================
# BEAMS
#=====================================================

/gate/source/addSource                       beam phaseSpace
/gate/source/beam/addPhaseSpaceFile          output/PhS_source_secondary/Particles_30MeV_5_5mm.root
/gate/source/beam/setParticleType            neutron
/gate/source/beam/attachTo                   target
/gate/source/beam/useRandomSymmetry          true

#=====================================================
# START BEAMS
#=====================================================
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/noGlobalOutput
/gate/application/setTotalNumberOfPrimaries 11024771
/gate/application/start
