
/vis/open OGLIQt
/vis/drawVolume
/vis/viewer/flush
/tracking/storeTrajectory             1
/vis/scene/add/trajectories
/vis/scene/endOfEventAction           accumulate
/vis/viewer/set/viewpointThetaPhi     180. 0. deg
/vis/viewer/zoom 		      3

/vis/scene/add/axes            350.05 0 0 250 mm
/vis/scene/add/text            10 0 0 cm  20 0 0   X
/vis/scene/add/text            0 10 0 cm  20 0 0   Y
/vis/scene/add/text            0 0 10 cm  20 0 0   Z
/vis/viewer/set/auxiliaryEdge true
